# Generated by Django 4.2.1 on 2023-06-15 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttPortalMemberModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('nationalID', models.CharField(blank=True, max_length=1000, null=True)),
                ('age', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1000, null=True)),
                ('occupation', models.CharField(blank=True, max_length=1000, null=True)),
                ('region', models.CharField(blank=True, choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Bukoba', 'Bukoba'), ('Mpanda', 'Mpanda'), ('Kigoma', 'Kigoma'), ('Moshi', 'Moshi'), ('Lindi', 'Lindi'), ('Babati', 'Babati'), ('Musoma', 'Musoma'), ('Mbeya', 'Mbeya'), ('Zanzibar City', 'Zanzibar City'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Wete', 'Wete'), ('Chake-Chake', 'Chake-Chake'), ('Kibaha', 'Kibaha'), ('Sumbawanga', 'Sumbawanga'), ('Songea', 'Songea'), ('Shinyanga', 'Shinyanga'), ('Bariadi', 'Bariadi'), ('Singida', 'Singida'), ('Vwawa', 'Vwawa'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Mkokotoni', 'Mkokotoni'), ('Koani', 'Koani')], max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'attPortal Members',
            },
        ),
    ]
